### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Abel-Ken** [TheQuinbox/recmon#5]
Hey give me your telegram contact

**Comment by trypsynth** [comment]
Interesting choice, opening an issue against a Hammerspoon, just to ask for Telegram info 😬

Closing this, as it is *not* an issue with the project, but rather, someone asking, quite rudely I might add, for my contact information. Pro tip: Going "Hey do this right now" is not how you get people to do things. That might be a language issue, but just throwing it out there.

What do you need it for?

**Comment by Abel-Ken** [comment]
Lol 😂... 

I was asking that to contact you!

**Comment by trypsynth** [comment]
Uh. Telegram would require me to give you my phone number, which... I don't give out my phone number to strangers online when they ask for it for (hopefully) obvious reasons. There are multiple ways to contact me publically, though. My Twitter is on my profile, as is my email.

**Comment by Abel-Ken** [comment]
Alright you have said well... Here is my telegram contact @Kennedoski1
